from __future__ import annotations

from typing import Protocol

from .models import DomainEvent, Memory, Relationship, TemporalFact


class MemoryStore(Protocol):
    def put(self, memory: Memory) -> None: ...
    def get(self, memory_id: str) -> Memory | None: ...
    def delete(self, memory_id: str) -> bool: ...
    def list(self, tenant_id: str) -> list[Memory]: ...


class TimelineStore(Protocol):
    def put_fact(self, fact: TemporalFact) -> None: ...
    def facts(self, tenant_id: str, entity: str | None = None, attribute: str | None = None) -> list[TemporalFact]: ...


class GraphStore(Protocol):
    def add_relationship(self, relationship: Relationship) -> None: ...
    def neighbors(self, tenant_id: str, node: str) -> list[Relationship]: ...


class EventBus(Protocol):
    def publish(self, event: DomainEvent) -> None: ...
    def events(self, tenant_id: str) -> list[DomainEvent]: ...

